{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d12c057e-0e8b-4742-82ed-61e68b347567",
   "metadata": {},
   "outputs": [],
   "source": [
    "#####################################################################################\n",
    "# Application of SMC² for mpox\n",
    "# This script loads mpox data and applies the eSMC² algorithm.\n",
    "#####################################################################################\n",
    "\n",
    "# === Import necessary libraries ===\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "from scipy.stats import truncnorm, uniform, norm\n",
    "from smc2 import ESMC_squared \n",
    "import matplotlib.pyplot as plt\n",
    "# Load data\n",
    "monkeypox = pd.read_csv('monkeypox_US.csv')\n",
    "\n",
    "# Rename and prepare columns\n",
    "monkeypox.rename(columns={'Epi_date_v3': 'Date'}, inplace=True)\n",
    "monkeypox['Date'] = pd.to_datetime(monkeypox['Date'])\n",
    "\n",
    "# Filter to include data up to Dec 8, 2022\n",
    "monkeypox = monkeypox[monkeypox['Date'] <= '2022-12-08']\n",
    "\n",
    "plt.figure(figsize=(10, 4))\n",
    "plt.plot(monkeypox['Date'], monkeypox['Cases'], color='dodgerblue', lw=2)\n",
    "plt.xlabel('Date', fontsize=14)\n",
    "plt.ylabel('Daily Confirmed Cases', fontsize=14)\n",
    "plt.title('U.S. Monkeypox (Mpox) Daily Cases', fontsize=16)\n",
    "plt.grid(True, linestyle='--', alpha=0.5)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "#####################################################################################\n",
    "# STEP 2: Define priors for states and parameters\n",
    "#####################################################################################\n",
    "\n",
    "# --- Initial state priors (state_info) ---\n",
    "state_info = {\n",
    "   'S': {'prior': truncnorm((0-329999990)/1e-1, (330000000-329999990)/1e-1, loc=329999990, scale=1e-1), 'transf': 'none'},\n",
    "    'E': {'prior': uniform(loc=0, scale=0), 'transf': 'none'},\n",
    "    'I': {'prior': truncnorm((1-10)/1e-1, (15-10)/1e-1, loc=10, scale=1e-1), 'transf': 'none'},\n",
    "    'R': {'prior': uniform(loc=0, scale=0), 'transf': 'none'},\n",
    "    'Z': {'prior': uniform(loc=1, scale=1), 'transf': 'none'},\n",
    "    'B': {'prior': uniform(loc=0.2, scale=0.3-0.2), 'transf': 'log'},\n",
    "}\n",
    "\n",
    "# --- Parameter priors (theta_info) ---\n",
    "theta_info = {\n",
    "    'alpha': {'prior': truncnorm((1/21-1/7)/0.05, (1/3-1/7)/0.05, loc=1/7, scale=0.05), 'transf': 'none'},\n",
    "    'gamma': {'prior': uniform(loc=1/28, scale=1/14-1/28), 'transf': 'none'},\n",
    "    'nu_beta': {'prior': uniform(loc=0, scale=0.3), 'transf': 'none'},\n",
    "    'phi': {'prior': uniform(loc=0, scale=0.05), 'transf': 'none'},\n",
    "}\n",
    "\n",
    "np.random.seed(123)\n",
    "\n",
    "esmc2_results = ESMC_squared(\n",
    "    initial_state_info=state_info,\n",
    "    initial_theta_info=theta_info,\n",
    "    observed_data=monkeypox['Cases'],\n",
    "    num_state_particles=200,\n",
    "    num_theta_particles=1000,\n",
    ")\n",
    "\n",
    "\n",
    "# Print the Marginal log-likelihood\n",
    "print(\"Marginal log-likelihood:\", esmc2_results['margLogLike'])\n",
    "\n",
    "\n",
    "\n",
    "#####################################################################################\n",
    "# STEP 4:   State visualization\n",
    "#####################################################################################\n",
    "\n",
    "from smc_visualization import*\n",
    "import seaborn as sns\n",
    "\n",
    "\n",
    "ci_levels = [50, 75, 90, 95]  # CI levels to plot\n",
    "mean_color ='blue'\n",
    "ci_color = 'gray'       \n",
    "window = 1 \n",
    "fontsize_axis = 15\n",
    "\n",
    "# Extract particle trajectories\n",
    "matrix_state = trace_smc(esmc2_results['trajState'])\n",
    "matrix_theta = trace_smc(esmc2_results['trajtheta'])\n",
    "\n",
    "# Compute effective reproduction number Rₜ\n",
    "gamma = np.mean(matrix_theta['gamma'][:, -1])\n",
    "matrix_state['Rt'] = matrix_state['B'] / gamma\n",
    "fig, axs = plt.subplots(3, 1, figsize=(10, 4*3))\n",
    "\n",
    "# New infections\n",
    "plot_smc(matrix_state['Z'], Date=monkeypox['Date'], ax=axs[0], mean_color=mean_color, ci_color=ci_color, label='Mean', window=window, ci_levels=ci_levels)\n",
    "axs[0].scatter(monkeypox['Date'], monkeypox['Cases'], color='orange', edgecolor='k', s=20, label='Observed')\n",
    "axs[0].set_xlabel('Date', fontsize=fontsize_axis)\n",
    "axs[0].set_ylabel('Daily cases', fontsize=fontsize_axis)\n",
    "axs[0].tick_params(axis='x', labelsize=14)\n",
    "axs[0].tick_params(axis='y', labelsize=16)\n",
    "axs[0].legend()\n",
    "\n",
    "# Transmission rate βₜ\n",
    "plot_smc(matrix_state['B'], Date=monkeypox['Date'], ax=axs[1], mean_color=mean_color, ci_color=ci_color, label='Mean', window=window, ci_levels=ci_levels)\n",
    "axs[1].set_xlabel('Date', fontsize=fontsize_axis)\n",
    "axs[1].set_ylabel(r'Transmission rate $\\beta_t$', fontsize=fontsize_axis)\n",
    "axs[1].tick_params(axis='x', labelsize=14)\n",
    "axs[1].tick_params(axis='y', labelsize=16)\n",
    "\n",
    "\n",
    "# Effective reproduction number Rₜ\n",
    "plot_smc(matrix_state['Rt'], ax=axs[2] , Date=monkeypox['Date'], mean_color=mean_color, ci_color=ci_color, label='Mean', window=window, ci_levels=ci_levels)\n",
    "axs[2].axhline(1, color='r', linestyle='--', lw=2)\n",
    "axs[2].set_xlabel('Date', fontsize=fontsize_axis)\n",
    "axs[2].set_ylabel(r'Reproduction number $R_0(t)$', fontsize=fontsize_axis)\n",
    "axs[2].tick_params(axis='x', labelsize=14)\n",
    "axs[2].tick_params(axis='y', labelsize=16)\n",
    "\n",
    "\n",
    "for ax in axs:\n",
    "    ax.spines['top'].set_visible(False)\n",
    "    ax.spines['right'].set_visible(False)\n",
    "    ax.set_facecolor('white')\n",
    "    ax.grid(True, alpha=0.3)\n",
    "    ax.legend(fontsize=16)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "\n",
    "#####################################################################################\n",
    "# STEP 4:   Parameter visualization\n",
    "#####################################################################################\n",
    "\n",
    "\n",
    "import matplotlib.gridspec as gridspec\n",
    "from collections import OrderedDict\n",
    "\n",
    "# --- User settings ---\n",
    "\n",
    "mean_color = 'blue'\n",
    "ci_color = 'gray'\n",
    "ci_levels = [50, 75, 90, 95]\n",
    "fontsize_axis = 20\n",
    "fontsize_label = 25\n",
    "fontsize_legend = 20\n",
    "\n",
    "theta_labels = {\n",
    "    'alpha': r'$\\alpha$',\n",
    "    'gamma': r'$\\gamma$',\n",
    "    'nu_beta': r'$\\nu_{\\beta}$',\n",
    "    'phi': r'$\\phi$',\n",
    "}\n",
    "\n",
    "# Extract priors using LaTeX labels as keys\n",
    "priors = {theta_labels[k]: v['prior'] for k, v in theta_info.items()}\n",
    "\n",
    "# Lower and upper bounds of priors\n",
    "prior_bounds = {key: priors[key].ppf(0.999) for key in priors.keys()}\n",
    "prior_supports = {key: priors[key].support()[0] for key in priors.keys()}  # <-- min bound\n",
    "\n",
    "N = len(matrix_theta)\n",
    "fig = plt.figure(figsize=(14, 4 * N))\n",
    "gs = gridspec.GridSpec(N, 2, width_ratios=[3.7, 1.3])\n",
    "handles, labels = [], []\n",
    "\n",
    "axs = np.empty((N, 2), dtype=object)\n",
    "for i in range(N):\n",
    "    axs[i, 0] = fig.add_subplot(gs[i, 0])\n",
    "    axs[i, 1] = fig.add_subplot(gs[i, 1])\n",
    "\n",
    "for i, key in enumerate(matrix_theta.keys()):\n",
    "    label_key = theta_labels[key]\n",
    "\n",
    "    plot_smc(matrix_theta[key], ax=axs[i, 0], Date=monkeypox['Date'],\n",
    "             mean_color=mean_color, ci_color=ci_color,\n",
    "             label='eSMC²', ci_levels=ci_levels)\n",
    "\n",
    "    axs[i, 0].set_xlabel('Date', fontsize=fontsize_axis)\n",
    "    axs[i, 0].set_ylabel(label_key, fontsize=fontsize_label)\n",
    "    axs[i, 0].tick_params(axis='x', labelsize=14)\n",
    "    axs[i, 0].tick_params(axis='y', labelsize=16)\n",
    "\n",
    "    if 'true_theta' in globals() and i < len(true_theta):\n",
    "        axs[i, 0].axhline(y=true_theta[i], color='orange', linestyle='--', lw=3, label='Ground truth')\n",
    "\n",
    "    # --- Posterior KDE ---\n",
    "    data = matrix_theta[key][:, -1]\n",
    "    sns.kdeplot(data, ax=axs[i, 1], color=ci_color, lw=2, label='Posterior')\n",
    "\n",
    "    if 'true_theta' in globals() and i < len(true_theta):\n",
    "        axs[i, 1].axvline(true_theta[i], color='orange', linestyle='--', lw=3, label='Ground truth')\n",
    "\n",
    "    # --- Prior PDF ---\n",
    "    x_min = prior_supports[label_key]\n",
    "    x_max = max(data.max(), prior_bounds[label_key])\n",
    "    x_vals = np.linspace(x_min, x_max, 500)\n",
    "    axs[i, 1].plot(x_vals, priors[label_key].pdf(x_vals),\n",
    "                   color='green', lw=3, linestyle='--', label='Prior')\n",
    "\n",
    "    axs[i, 1].set_xlabel(label_key, fontsize=fontsize_label)\n",
    "    axs[i, 1].set_ylabel('Density', fontsize=fontsize_axis)\n",
    "    axs[i, 1].tick_params(axis='x', labelsize=14)\n",
    "    axs[i, 1].tick_params(axis='y', labelsize=16)\n",
    "\n",
    "    for ax in [axs[i, 0], axs[i, 1]]:\n",
    "        ax.spines['top'].set_visible(False)\n",
    "        ax.spines['right'].set_visible(False)\n",
    "        ax.spines['left'].set_linewidth(1.2)\n",
    "        ax.spines['bottom'].set_linewidth(1.2)\n",
    "        ax.set_facecolor('white')\n",
    "        ax.grid(True, alpha=0.2)\n",
    "\n",
    "    h, l = axs[i, 1].get_legend_handles_labels()\n",
    "    handles.extend(h)\n",
    "    labels.extend(l)\n",
    "\n",
    "by_label = OrderedDict(zip(labels, handles))\n",
    "fig.legend(by_label.values(), by_label.keys(), loc='lower center',\n",
    "           fontsize=fontsize_legend, ncol=4, frameon=False,\n",
    "           markerscale=3, handlelength=3, handletextpad=0.8)\n",
    "\n",
    "plt.tight_layout(h_pad=2, w_pad=3, rect=[0, 0.05, 1, 1])\n",
    "plt.show()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bcbb871f-00f8-4166-9086-b2b86b0a5d1e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
